name: Trigger auto deployment for go-file

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/go-file-AutoDeployTrigger-11f258d8-4ffe-4101-945e-a077febbe1cc.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GOFILE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: gofile6d225f.azurecr.io
          registryUsername: ${{ secrets.GOFILE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GOFILE_REGISTRY_PASSWORD }}
          containerAppName: go-file
          resourceGroup: thanhtt
          imageToBuild: gofile6d225f.azurecr.io/go-file:${{ github.sha }}
          
            

     

